### ISSUE TITLE
Blurred chats on the left

### ISSUE THREAD

**Issue by florisdg** [vednoc/onyx#37]
I remember this theme used to have blurred chats on the left, (like in the README.md)but haven't seen it for a while now. I decided to do it myself and did it with the following code:

```css
#pane-side > div > div > div > div > div > ._3mMX1 *,
#pane-side > div > div > div > div > div > div:hover * {
	filter: blur(0px) !important;
}

#pane-side > div > div > div > div > div > div > div:nth-child(1),
#pane-side > div > div > div > div > div > div > div > div:nth-child(1) > div:nth-child(1),
#pane-side > div > div > div > div > div > div > div > div:nth-child(2) > div:nth-child(1) {
	filter: blur(6px);
}
```

It only blurs the ProfilePicture/Avatar, title and lastmessage. It does not blur the unread messages counter, time/date, pinned chats icons on the right. If a chat is selected that one stays unblurred to highlight which chat is open.

I hope this will be added back into the theme!

Edit: screenshot example:
![image](https://user-images.githubusercontent.com/23520068/59270413-b0534e80-8c51-11e9-87fa-39098a7697e0.png)
