### ISSUE TITLE
Fixing upload error Message, Group name input and Background of downloadable content

### ISSUE THREAD

**Issue by TwentyFourMinutes** [vednoc/onyx#48]
Background color of downloadable content.
![image](https://user-images.githubusercontent.com/36015290/65251905-64d5f980-daf8-11e9-80e3-f65fd2755e70.png)
Can be fixed with:
```css
._1mrMQ{
    background-color: var(--dark) !important;
}
```
Font color of input box while adding people to a group
![image](https://user-images.githubusercontent.com/36015290/65251970-7ae3ba00-daf8-11e9-9a80-36b7f58a6172.
Can be fixed with:
```css
._44uDJ {
    color:var(--light);
}
```

Font color of error message while uploading invalid File Types e.g. a folder.
![image](https://user-images.githubusercontent.com/36015290/65252114-b088a300-daf8-11e9-9f91-fdcdd2c87825.png)
```css
.azEEh{
    color:var(--light);
}
```
