### ISSUE TITLE
The new emojis in v1.6 aren't really better then before

### ISSUE THREAD

**Issue by TwentyFourMinutes** [vednoc/onyx#61]
So as the release v1.6 states, the annoying white backgrounds got removed and new fully transparent images are getting used.

> Backgrounds for emoji images in the emoji menu are now transparent for the first time ever.

I am not sure if I didn't understand something correct, but this doesn't seem like an improvement at all.

![image](https://user-images.githubusercontent.com/36015290/68535429-e6047c80-0342-11ea-9f5a-f153609ca43f.png)

![image](https://user-images.githubusercontent.com/36015290/68535453-2663fa80-0343-11ea-9772-5b8bcf445978.png)

**Comment by vednoc** [comment]
Weird. It was [confirmed] in another thread that it works. Steps to debug would be:
- Open DevTools and navigate to the Network section.
- Open emoji menu or quick selection and check whether new emoji images are being downloaded from `https://raw.githubusercontent.com/vednoc/wae/master/i/1-101.webp`.

Here is what it *should* look like:
![img](https://user-images.githubusercontent.com/18245694/68491422-1f59c100-024b-11ea-80a6-23405e87d2da.png)

[confirmed]: https://github.com/vednoc/onyx/issues/59#issuecomment-551890106

**Comment by tinyCoder32** [comment]
@TwentyFourMinutes check again, i guess you are mixing between onyx and another project on Stylus. Because I already tested the one with the square white background, it's a completely different style. Just double check, because vednoc's latest version works perfectly.

**Comment by vednoc** [comment]
> Here is what it _should_ look like:
> ![img](https://user-images.githubusercontent.com/18245694/68491422-1f59c100-024b-11ea-80a6-23405e87d2da.png)

Just for the reference, this screenshot is from v2 in #38, but the emoji images are ported back to v1 in dfbfd5d752fe84aa484eaa78bf143460742c35c7.

**Comment by TwentyFourMinutes** [comment]
Well I actually checked the source file and it looks totally fine:
![image](https://user-images.githubusercontent.com/36015290/68535682-8a3bf280-0346-11ea-8c81-a854dc4403ff.png)

Also the images are getting pulled from their website:
![image](https://user-images.githubusercontent.com/36015290/68535702-d71fc900-0346-11ea-80d0-29b43adf809c.png)

I also cleared all Local Storage weird... will do some further testing.

**Comment by tinyCoder32** [comment]
<img width="792" alt="image" src="https://user-images.githubusercontent.com/17817239/68535712-dfcccb00-0357-11ea-9e00-ff68f4663eb0.png">

Did you make sure you're not activating another style beside vednoc's?
Coz I think i've seen the same square design in another style.

**Comment by TwentyFourMinutes** [comment]
Well I am pretty sure actually:
![image](https://user-images.githubusercontent.com/36015290/68535732-80ff5580-0347-11ea-9ee9-032def4e8840.png)
I also cleared all my thumbnail caches and any others caches related to browsers.

**Comment by tinyCoder32** [comment]
But doesn't vednoc's style called "WhatsApp by Mew"?

**Comment by vednoc** [comment]
> But doesn't vednoc's style called "WhatsApp by Mew"?

The UserCSS version hosted on GitHub is called that. The one from USo is 'Dark WhatsApp Theme by Mew' or whatever. @TwentyFourMinutes try installing the UserCSS version from the readme to see if that changes anything.

**Comment by TwentyFourMinutes** [comment]
Well it is the same version, I just uninstalled the one I had installed and downloaded it directly from the README file. The name changed though, still same squares. I cleared all browser data again, but without any succes.

**Comment by TwentyFourMinutes** [comment]
I also can verify that the usercss I currently have installed contains the needed links:
![image](https://user-images.githubusercontent.com/36015290/68535825-db4ce600-0348-11ea-851f-b0900b1af46c.png)
But I can't see any network requests made to this uri.

**Comment by vednoc** [comment]
There's no need to clear local storage or anything like that. Something else is going wrong here. Perhaps it's an issue with specificity, so this *might* fix it, just drop it in a new stylesheet within DevTools.
```css
  .emojik.wa.b0 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/0.webp") !important}
  .emojik.wa.b1 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/1.webp") !important}
  .emojik.wa.b2 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/2.webp") !important}
  .emojik.wa.b3 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/3.webp") !important}
  .emojik.wa.b4 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/4.webp") !important}
  .emojik.wa.b5 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/5.webp") !important}
  .emojik.wa.b6 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/6.webp") !important}
  .emojik.wa.b7 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/7.webp") !important}
  .emojik.wa.b8 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/8.webp") !important}
  .emojik.wa.b9 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/9.webp") !important}
  .emojik.wa.b10 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/10.webp") !important}
  .emojik.wa.b11 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/11.webp") !important}
  .emojik.wa.b12 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/12.webp") !important}
  .emojik.wa.b13 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/13.webp") !important}
  .emojik.wa.b14 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/14.webp") !important}
  .emojik.wa.b15 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/15.webp") !important}
  .emojik.wa.b16 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/16.webp") !important}
  .emojik.wa.b17 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/17.webp") !important}
  .emojik.wa.b18 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/18.webp") !important}
  .emojik.wa.b19 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/19.webp") !important}
  .emojik.wa.b20 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/20.webp") !important}
  .emojik.wa.b21 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/21.webp") !important}
  .emojik.wa.b22 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/22.webp") !important}
  .emojik.wa.b23 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/23.webp") !important}
  .emojik.wa.b24 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/24.webp") !important}
  .emojik.wa.b25 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/25.webp") !important}
  .emojik.wa.b26 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/26.webp") !important}
  .emojik.wa.b27 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/27.webp") !important}
  .emojik.wa.b28 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/28.webp") !important}
  .emojik.wa.b29 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/29.webp") !important}
  .emojik.wa.b30 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/30.webp") !important}
  .emojik.wa.b31 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/31.webp") !important}
  .emojik.wa.b32 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/32.webp") !important}
  .emojik.wa.b33 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/33.webp") !important}
  .emojik.wa.b34 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/34.webp") !important}
  .emojik.wa.b35 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/35.webp") !important}
  .emojik.wa.b36 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/36.webp") !important}
  .emojik.wa.b37 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/37.webp") !important}
  .emojik.wa.b38 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/38.webp") !important}
  .emojik.wa.b39 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/39.webp") !important}
  .emojik.wa.b40 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/40.webp") !important}
  .emojik.wa.b41 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/41.webp") !important}
  .emojik.wa.b42 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/42.webp") !important}
  .emojik.wa.b43 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/43.webp") !important}
  .emojik.wa.b44 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/44.webp") !important}
  .emojik.wa.b45 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/45.webp") !important}
  .emojik.wa.b46 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/46.webp") !important}
  .emojik.wa.b47 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/47.webp") !important}
  .emojik.wa.b48 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/48.webp") !important}
  .emojik.wa.b49 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/49.webp") !important}
  .emojik.wa.b50 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/50.webp") !important}
  .emojik.wa.b51 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/51.webp") !important}
  .emojik.wa.b52 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/52.webp") !important}
  .emojik.wa.b53 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/53.webp") !important}
  .emojik.wa.b54 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/54.webp") !important}
  .emojik.wa.b55 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/55.webp") !important}
  .emojik.wa.b56 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/56.webp") !important}
  .emojik.wa.b57 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/57.webp") !important}
  .emojik.wa.b58 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/58.webp") !important}
  .emojik.wa.b59 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/59.webp") !important}
  .emojik.wa.b60 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/60.webp") !important}
  .emojik.wa.b61 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/61.webp") !important}
  .emojik.wa.b62 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/62.webp") !important}
  .emojik.wa.b63 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/63.webp") !important}
  .emojik.wa.b64 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/64.webp") !important}
  .emojik.wa.b65 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/65.webp") !important}
  .emojik.wa.b66 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/66.webp") !important}
  .emojik.wa.b67 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/67.webp") !important}
  .emojik.wa.b68 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/68.webp") !important}
  .emojik.wa.b69 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/69.webp") !important}
  .emojik.wa.b70 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/70.webp") !important}
  .emojik.wa.b71 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/71.webp") !important}
  .emojik.wa.b72 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/72.webp") !important}
  .emojik.wa.b73 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/73.webp") !important}
  .emojik.wa.b74 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/74.webp") !important}
  .emojik.wa.b75 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/75.webp") !important}
  .emojik.wa.b76 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/76.webp") !important}
  .emojik.wa.b77 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/77.webp") !important}
  .emojik.wa.b78 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/78.webp") !important}
  .emojik.wa.b79 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/79.webp") !important}
  .emojik.wa.b80 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/80.webp") !important}
  .emojik.wa.b81 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/81.webp") !important}
  .emojik.wa.b82 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/82.webp") !important}
  .emojik.wa.b83 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/83.webp") !important}
  .emojik.wa.b84 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/84.webp") !important}
  .emojik.wa.b85 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/85.webp") !important}
  .emojik.wa.b86 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/86.webp") !important}
  .emojik.wa.b87 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/87.webp") !important}
  .emojik.wa.b88 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/88.webp") !important}
  .emojik.wa.b89 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/89.webp") !important}
  .emojik.wa.b90 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/90.webp") !important}
  .emojik.wa.b91 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/91.webp") !important}
  .emojik.wa.b92 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/92.webp") !important}
  .emojik.wa.b93 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/93.webp") !important}
  .emojik.wa.b94 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/94.webp") !important}
  .emojik.wa.b95 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/95.webp") !important}
  .emojik.wa.b96 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/96.webp") !important}
  .emojik.wa.b97 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/97.webp") !important}
  .emojik.wa.b98 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/98.webp") !important}
  .emojik.wa.b99 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/99.webp") !important}
  .emojik.wa.b100 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/100.webp") !important}
  .emojik.wa.b101 {background-image: url("https://raw.githubusercontent.com/vednoc/wae/master/i/101.webp") !important}
```
